--case 'Q1':
SELECT IDP, NOM FROM PROF WHERE ANNEE_NAISSANCE = 1972;
--case 'Q2':
SELECT * FROM DEVOIR WHERE NIVEAU = '4eme';
--case 'Q3':
SELECT * FROM ETABLISSEMENT WHERE RNE LIKE '034%';
--case 'Q4':
SELECT IDEX, NIVEAU, PROPRIETAIRE FROM EXERCICE WHERE CONTENU LIKE '%calculer%';
--case 'Q5':
SELECT IDEX, NIVEAU, PROPRIETAIRE FROM EXERCICE WHERE NIVEAU IN ('5eme', '4eme', '3eme') ORDER BY DATE_CREATION DESC;
--case 'Q6':
SELECT DISTINCT EXERCICE.IDEX, CONTENU.BAREME FROM EXERCICE JOIN CONTENU ON EXERCICE.IDEX = CONTENU.IDEX ORDER BY CONTENU.BAREME DESC;
--case 'Q7':
SELECT IDEX, DATE_CREATION FROM EXERCICE WHERE DATE_CREATION BETWEEN TO_DATE('2019-01-01', 'YYYY-MM-DD') AND TO_DATE('2019-01-31', 'YYYY-MM-DD') ORDER BY DATE_CREATION DESC;
--case 'Q8':
SELECT NOTE FROM PASSAGE WHERE IDEL = 4 AND IDD = 6;
--case 'Q9':
SELECT NOTE FROM PASSAGE WHERE IDD = 7 AND IDEL = (SELECT IDEL FROM ELEVE WHERE NOM = 'Dupont' AND PRENOM = 'Maxime');
--case 'Q10':
SELECT P.NOM FROM PROF P JOIN ETABLISSEMENT E ON P.RNE = E.RNE WHERE P.VILLE = E.LOCALITE;
--case 'Q11':
SELECT DISTINCT E.NOM, E.PRENOM FROM ELEVE E JOIN PASSAGE P ON E.IDEL = P.IDEL;
--case 'Q12':
SELECT DISTINCT E.nomEtab FROM ETABLISSEMENT E JOIN DEVOIR D ON E.RNE = D.RNE WHERE D.dateDevoir >= SYSDATE;
--case 'Q13':
SELECT E.NOM, E.PRENOM FROM ELEVE E JOIN PASSAGE P ON E.IDEL = P.IDEL WHERE E.NIVEAU <> (SELECT D.NIVEAU FROM DEVOIR D WHERE D.IDD = P.IDD);
--case 'Q14':
SELECT DISTINCT E.NOM, E.PRENOM FROM ELEVE E JOIN PASSAGE P ON E.IDEL = P.IDEL JOIN CONTENU C ON P.IDD = C.IDD WHERE C.BAREME >= 6;
--case 'Q15':
SELECT COUNT(*) AS nombre_eleves FROM ELEVE;
--case 'Q16':
SELECT SUM(BAREME) AS total_points FROM CONTENU WHERE IDD = 4;
--case 'Q17':
SELECT COUNT(*) AS nombre_profs FROM PROF WHERE IDP NOT IN (SELECT DISTINCT PROPRIETAIRE FROM EXERCICE);
--case 'Q18':
SELECT COUNT(*) AS nombre_devoirs FROM PASSAGE WHERE IDEL = (SELECT IDEL FROM ELEVE WHERE NOM = 'Rami' AND PRENOM = 'Alexandre');
--case 'Q19':
SELECT MIN(BAREME) AS min_bareme FROM CONTENU WHERE IDD = 2;
--case 'Q20':
SELECT AVG(BAREME) AS moyenne_bareme FROM CONTENU WHERE IDD = 4;
--case 'Q21':
SELECT MAX(BAREME) - MIN(BAREME) AS etendue_bareme FROM CONTENU WHERE IDD = 6;
--case 'Q22':
SELECT P.NOM, COUNT(D.IDD) AS nombre_devoirs FROM PROF P JOIN DEVOIR D ON P.IDP = D.PROF_CREATEUR GROUP BY P.NOM ORDER BY nombre_devoirs DESC;
--case 'Q23':
SELECT MAX(NOTE) AS meilleure_note FROM PASSAGE WHERE IDEL = (SELECT IDEL FROM ELEVE WHERE NOM = 'Dupont' AND PRENOM = 'Arnaud');
--case 'Q24':
SELECT E.NOM, E.PRENOM FROM ELEVE E WHERE E.IDEL NOT IN (SELECT DISTINCT IDEL FROM PASSAGE);
--case 'Q25':
SELECT DISTINCT P.NOM FROM PROF P LEFT JOIN EXERCICE E ON P.IDP = E.PROPRIETAIRE LEFT JOIN DEVOIR D ON P.IDP = D.PROF_CREATEUR WHERE E.IDEX IS NOT NULL OR D.IDD IS NOT NULL;
--case 'Q26':
SELECT DISTINCT P.NOM FROM PROF P JOIN EXERCICE E ON P.IDP = E.PROPRIETAIRE JOIN DEVOIR D ON P.IDP = D.PROF_CREATEUR;
--case 'Q27':
SELECT N.NIVEAU FROM NIVEAU N WHERE N.NIVEAU NOT IN (SELECT DISTINCT E.NIVEAU FROM EXERCICE E);
--case 'Q28':
SELECT E.IDEX, E.CONTENU FROM EXERCICE E WHERE E.IDEX NOT IN (SELECT DISTINCT C.IDEX FROM CONTENU C);
default:
    DBMS_OUTPUT.PUT_LINE('Énumérez simplement les requêtes SQL.');
